os:
  - linux

language: python

python:
  - 3.5
  - 3.6

install:
  - pip install coveralls
  - pip install -e .

script:
  - coverage run --source=. -m unittest discover -s tests/ -v

after_script:
  # Send results to https://coveralls.io/.
  - coveralls