# Travis CI only supports Python builds for Linux (at this moment)
os:
  - linux

language: python

python:
  - 3.5
  - 3.6

install:
  - pip install coveralls
  - pip install -e .

script: scripts/travis.sh

