# Travis CI only supports Python builds for Linux (at this moment)
os:
  - linux

language: python

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

# command to install dependencies
install:
  - pip install coveralls
  - pip install -e .

# command to run tests
script: scripts/travis.sh

after_success:
  - coveralls
  
