name: New Feature

description: Suggest a new feature

title: "[Feature]: "
labels: ["feature"]
projects: ["andz"]

assignees:
  - nbro

body:

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature type
      description: Is the new feature an algorithm or a data structure?
      options:
        - Algorithm
        - Data structure
      default: 0
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Describe the feature and why it should be implemented
    validations:
      required: true
